name: Publish new release

on:
  pull_request:
    branches:
    - master
  release:
    types: [published]

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
    
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 3.1.x

      - name: Restore project
        run: dotnet restore

      - name: Build package
        run: dotnet build --configuration Release --no-restore

      #TODO: - name: Test package 

      - name: Store build files
        uses: actions/upload-artifact@v3
        with:
          name: build_files
          path: ./bin
          retention-days: 1
          if-no-files-found: error

  create_nuget:
    runs-on: ubuntu-latest
    needs: [ build_test ]
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 3.1.x

      - name: Get build files
        uses: actions/download-artifact@v3
        with:
          name: build_files
          path: ${{ env.NuGetDirectory }}
      
      - name: Create package
        run: dotnet pack --configuration Release --output ./nupkg

      - name: Store nuget package
        uses: actions/upload-artifact@v3
        with:
          name: nuget_package
          path: ./nupkg/*.nupkg
          retention-days: 1
          if-no-files-found: error